
version: '3.7'
services:
  db:
    image: postgres:latest
    volumes:
      - ./db/pgsql:/var/lib/postgresql/data
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
